[2017-11-15 20:05:40] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:06:08] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:06:19] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:06:27] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:09:03] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:09:11] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:09:20] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:10:58] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:12:26] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:12:39] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:13:04] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:26:59] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:27:49] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:40:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:31:12] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:41:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:31:43] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:41:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2017-11-15 20:32:06] [ERROR] Error: ddd
    at Context.it (/Users/richen/Workspace/nodejs/thinkkoa/test/think.test.js:41:27)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:443:10)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:361:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:295:14)
    at /Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runnable.js:340:7)
    at next (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/richen/Workspace/nodejs/thinkkoa/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
